### ISSUE TITLE
font problems

### ISSUE THREAD

**Issue by bigtone1284** [bigtone1284/Bones#32]
@htella @harimohanraj89 @DrRobotmck , happy new years guys.

I was having trouble using a custom font for my app:

http://www.ambor.com/public/dice/dice.html

http://www.ambor.com/hb/webdice.html

I downloaded it and the font works locally but on heroku it does not.  

I was getting an error in the js console that it was because I was using a source 'http:....' not 'https:...', changed taht but did not get the font in heroku.  (also cleared browser cache).  

I also tried to include the .ttf file for the font itself in my vendor/assets folder, and then list that as a source.  That also didn't work.  

When I try to store it in my vendor/assets folder, and then list it as the source, I get an error in my js as listed below:

GET http://localhost:3000/vendor/assets/fonts/dice(1).ttf 

I think I am close but am not declaring the src url of where my font lives very well.

**Comment by harimohanraj89** [comment]
Assets get fingerprinted in production. Remember we had to use helpers like `asset_path` to refer to image paths in our CSS to ensure that things work in production? You have to use similar helpers to refer to the `.ttf` file in your `/vendor/assets` folder. This may resolve the issue.

**Comment by bigtone1284** [comment]
@harimohanraj89 @htella @DrRobotmck 

Still not getting this.  

I have changed to include all possible font files in a app/fonts folder.  

Then I added these helpers to my application.css.erb file:

    @font-face {
    font-family: 'dicemedium';
    src: url("<%= font_url("dice.eot") %>");
    src: url("<%= font_url("dice.eot?#iefix") %>") format('embedded-opentype'),
         url("<%= font_url("dice.woff2") %>") format('woff2'),
         url("<%= font_url("dice.woff") %>") format('woff'),
         url("<%= font_url("dice.ttf") %>") format('truetype'),
         url("<%= font_url("dice.svg#dicemedium") %>") format('svg');
    font-weight: normal;
    font-style: normal;

}


Then I added this to my application.rb:

 config.assets.enabled = true
    # Add the fonts path
    config.assets.paths << "#{Rails.root}/app/assets/fonts"

    # Precompile additional assets
    config.assets.precompile << /\.(?:svg|eot|woff|ttf)\z/

Still not working in production....but working locally.

Any other ideas where to check to fix this problem?  

http://www.ambor.com/public/dice/dice.html

That is the link where I downloaded the font from.  Works local after I have downloaded.

**Comment by bigtone1284** [comment]
I also have rake precompiled my assets.

**Comment by harimohanraj89** [comment]
Are your fonts in `app/fonts` or `app/assets/fonts`? They should be in the latter.
